### ISSUE TITLE
Videos of talks

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/prl-prg.github.io#12]
@janvitek  asked if we could add links to videos of talks. I know we have some links among the papers, but how about making this a separate tab, so it doesn't get drowned out by other information?

**Comment by ulysses4ever** [comment]
I think having a tag `[video]` along with `[PDF]` is actually OK. Moreover, I think the number of top menu items is kinda huge already.

**Comment by kondziu** [comment]
My two objections are as follows:
1. There will be talks that don't have a paper attached (eg. summer school).
2. Having the talks more visible would drive a larger variety of people to see them, esp. people who would not be interested in papers.

I agree about the tag bloat. But maybe we can find a more prominent place to display them? Maybe front page?

**Comment by ulysses4ever** [comment]
Point 1 is fair, yes. Could we accommodate Talks on the Events page probably?

Front page has huge picture: not everyone scroll down and could instead browse the menu, I think.

**Comment by kondziu** [comment]
We have a lot of fairly boring text on the front page though, it wouldn't hurt to add something interesting. A section with a selection of stuff the lab did that is interesting (like Peťa's talk).

**Comment by ulysses4ever** [comment]
Agreed on boring. We could place one or two embedded videos on the front
page (then we have to update it once in a while), but this seems 
orthogonal to where-to-store-talks issue.

**Comment by julbinb** [comment]
I would rename "Publications" menu item into smth like "Papers&Talks" and put links to videos into the same page. Like this:

### 2017
#### Talks
* Link1
* Link2
#### Publications
* Paper1
* Paper2

**Comment by fikovnik** [comment]
How about to _feature_ videos on the front page, i.e. we can have the News at the top (ideally making the image a bit smaller - dancing house is cool, but is it really that much :-) ). And the _mandatory_ about  section at the bottom.

**Comment by ulysses4ever** [comment]
_News_ section with some videos sounds good to me. This seems orthogonal to finding a spot to store all of them, isn't it?

**Comment by fikovnik** [comment]
Next to the paper in publications should be OK for now I think. We could probably make the presentation better than just `[PDF][Talk]` - perhaps embed Youtube or highligted link _Watch the talk_? Anyone with CSS / HTML skills?
